export enum ORDER_MSG {
  CREATE_ORDER = 'CREATE_ORDER',
  FIND_ALL_ORDER = 'FIND_ALL_ORDER',
}

export enum RECIPE_MSG {
  CREATE_RECIPE = 'CREATE_RECIPE',
  FIND_ONE_RECIPE_BY_ID = 'FIND_ONE_RECIPE_BY_ID',
  FIND_ALL_RECIPE = 'FIND_ALL_RECIPE',
  FIND_ONE_RANDOM_RECIPE = 'FIND_ONE_RANDOM_RECIPE',
}
