export enum INGREDIENT_MSG {
  CREATE_INGREDIENT = 'CREATE_INGREDIENT',
  GET_ONE_BY_NAME_INGREDIENT = 'GET_ONE_BY_NAME_INGREDIENT',
}

export enum INVENTORY_MSG {
  UPDATE_INVENTORY = 'UPDATE_INVENTORY',
  GET_INVENTORY = 'GET_INVENTORY',
}
